language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "4"

env:
  - V_SERVE_STATIC=1.7.2
  - V_SERVE_STATIC=latest

before_script:
  - npm uninstall serve-static
  - npm install serve-static@$V_SERVE_STATIC
